const HOST="com.ideveloper.udownload.native";const DEFAULTS={intercept:true,sendCookies:true};const recent=new Map();
async function settings(){return browser.storage.local.get(DEFAULTS)}
async function sendNative(message){try{return await browser.runtime.sendNativeMessage(HOST,message)}catch(e){return {ok:false,error:e.message}}}
async function cookieHeader(url){const s=await settings();if(!s.sendCookies||!/^https?:/i.test(url))return"";try{return (await browser.cookies.getAll({url})).map(c=>`${c.name}=${c.value}`).join("; ")}catch(_){return""}}
function createMenus(){browser.menus.removeAll().then(()=>{browser.menus.create({id:"udm-link",title:"Download with UDM",contexts:["link","image","video","audio"]});browser.menus.create({id:"udm-selected",title:"Download selected links with UDM",contexts:["selection","page"]});browser.menus.create({id:"udm-all",title:"Download all links with UDM",contexts:["page"]})})}
browser.runtime.onInstalled.addListener(createMenus);createMenus();
browser.menus.onClicked.addListener(async(info,tab)=>{if(info.menuItemId==="udm-link"){const url=info.linkUrl||info.srcUrl;if(url)await sendNative({action:"add_url",url,pageUrl:info.pageUrl||tab.url||"",cookies:await cookieHeader(url)});return}const mode=info.menuItemId==="udm-selected"?"selected":"all";const links=await browser.tabs.sendMessage(tab.id,{action:"collect-page-links",mode}).catch(()=>[]);await sendNative({action:"select_links",links,pageUrl:tab.url||""})});
browser.runtime.onMessage.addListener(async message=>{if(message.action==="collect"){const tabs=await browser.tabs.query({active:true,currentWindow:true});const tab=tabs[0];const links=tab?await browser.tabs.sendMessage(tab.id,{action:"collect-page-links",mode:message.mode||"all"}).catch(()=>[]):[];return sendNative({action:"select_links",links,pageUrl:tab?.url||""})}if(message.action==="ping")return sendNative({action:"ping"})});
browser.downloads.onCreated.addListener(async item=>{const s=await settings();if(!s.intercept)return;const url=item.finalUrl||item.url||"";if(!/^(https?|ftp):/i.test(url))return;const now=Date.now();if(recent.has(url)&&now-recent.get(url)<5000)return;recent.set(url,now);setTimeout(()=>recent.delete(url),6000);const ready=await sendNative({action:"ping"});if(!ready||ready.ok===false)return;try{await browser.downloads.cancel(item.id)}catch(_){}try{await browser.downloads.erase({id:item.id})}catch(_){}await sendNative({action:"add_url",url,filename:item.filename?item.filename.split(/[\\/]/).pop():"",referrer:item.referrer||"",cookies:await cookieHeader(url),intercepted:true})});
